# This file generated by AI

set -e

# cd "$(dirname "$0")/.."

OUTPUT="$(pwd)"
APP_NAME="AuriBuds"
DMG_NAME="$APP_NAME.dmg"
MOUNT_NAME="/Volumes/$APP_NAME"
BACKGROUND="$(pwd)/dmgbg@2x.png"
SRC="$(pwd)/app/$APP_NAME.app"

# Remove old DMG outputs
if ls *.dmg 1> /dev/null 2>&1; then
  echo "Existing DMG found, removing..."
  rm -f *.dmg
fi

# Detach previously mounted DMG volume if it still exists
if [ -d "$MOUNT_NAME" ]; then
  echo "Mounted DMG volume found, detaching..."
  hdiutil detach "$MOUNT_NAME" -force || true
fi

# Restart Finder to reduce stale view/layout cache issues
killall Finder >/dev/null 2>&1 || true
sleep 1

if [ ! -d "$SRC" ]; then
  echo "App not found: $SRC"
  echo "Did you run tauri build?"
  exit 1
fi

if [ ! -f "$BACKGROUND" ]; then
  echo "Background image not found: $BACKGROUND"
  exit 1
fi

create-dmg \
  --volname "$APP_NAME" \
  --window-size 400 640 \
  --icon-size 120 \
  --text-size 14 \
  --icon "$APP_NAME.app" 200 164 \
  --app-drop-link 200 450 \
  --background "$BACKGROUND" \
  "$OUTPUT/$DMG_NAME" \
  "$(dirname "$SRC")"